apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xblobstorages.platform.demo
spec:
  group: platform.demo

  names:
    kind: XBlobStorage
    plural: xblobstorages

  scope: Cluster

  versions:
    - name: v1alpha1
      served: true
      referenceable: true

      schema:
        openAPIV3Schema:
          type: object

          properties:
            spec:
              type: object

              properties:
                location:
                  type: string

                storageName:
                  type: string

                environment:
                  type: string

                size:
                  type: string

              required:
                - location
                - storageName
                - size
                - environment