apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: blobstorage-local

spec:
  compositeTypeRef:
    apiVersion: platform.demo/v1alpha1
    kind: XBlobStorage

  mode: Pipeline

  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform

      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources

        resources:
          - name: namespace
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                providerConfigRef:
                  name: local
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Namespace
                    metadata:
                      name: placeholder

            patches:
              - fromFieldPath: spec.storageName
                toFieldPath: spec.forProvider.manifest.metadata.name